### ISSUE TITLE
Andmeusk kodulehele

### ISSUE THREAD

**Issue by infokujur** [okestonia/andmekool#1]
Selleks on vaja vana oke veeb üle vaadata ja luua /andmeusk

**Comment by boamaod** [comment]
Meil on kodulehe issue https://github.com/okestonia/esindus/issues/51, kus on plaanitavate muudatuste kohta info napp -- mida tähendab andmeusk ja kuidas see haagib selle materjaliga, mis juba meie kodulehel on/oli?

**Comment by infokujur** [comment]
Imho võiks koduleht kajastada tegevusliine (projekte), mida OKE teeb. Aga saan Nula inkubaatori töö jaoks ka täiesti eraldi lehe teha, kui tekitab küsimusi.
OKE WWW on olnud @boamaod ja @peepkungas peal. Palun arutage seda siis okestonia/esindus#51 teemas edasi, kuidas www-ga jääb.

**Comment by infokujur** [comment]
https://andmeusk.voog.com - vaja sisu sisse kanda.
