### ISSUE TITLE
tellimusvormi testida ja kohendada

### ISSUE THREAD

**Issue by teelepehk** [okestonia/andmekool#19]
@pilbastex, palun testi tellimusvormi - et kas kõik töötab 
@infokujur ja @MarkoVaik - kas küsimused sobivad? 

http://andmekool.voog.com/

**Comment by infokujur** [comment]
Hea küsimustik. Seda esimest küsimust mõtleks veel "Millist probleemi soovid andmete abil lahendada? Kirjelda oma asutuse või valdkonna vajadust." See on liiga keeruline esimeseks küsimuseks, inimene võib ennast kinni mõelda sinna.
Saada sama info kätte jah/ei vastustega? A'la kas praegu võtab liiga kaua aega, et andmeid kätte saada? Kas inimesed tunnevad, et info ei liigu? Kas osapooltel on ülevaade protsessist?

**Comment by pilbastex** [comment]
"millal soovin koolitust saada" võiks olla võimalik sisestada mitmed erinevad kuupäevad või ajavahemiku(d)
Tulemuste seas pole vast väga pointi kliendi täpsemat soovi pirukana kuvada aga see koolitusjärgne pirukanälg on mõistetav :)
Olen päri, et kliendil ei tohiks lasta end kinni mõelda. Kindlasti tunneb klient seda tööd, mida ta teeb ja oskab samm-sammult kirjeldada (loodetavasti koos ajakuluga) oma praegust tegevust. Valikvastustega seda päris kätte ei saa ja mil moel me neist "jah" ja "ei" vastustest üldse lähtuda saame? Valikvastuseid tasub ehk kaaluda ressursikulu hindamisel, kus saame ette anda kategooriad ja vahemikud.

**Comment by teelepehk** [comment]
Kohendasin tellimusvormi, tegin alguse lihtsamaks (valikvastused). 
Vorm ei tohiks kliendile sisestatud andmeid pirukana näidata - see peaks aind meile, kellel admin-juurdepääs, nähtav olema.
