### ISSUE TITLE
Tallinna LV liftikõne

### ISSUE THREAD

**Issue by pilbastex** [okestonia/andmekool#3]
Tekitada huvi Haidak&co-s ning jagada siin tulemusi. Raporteerin digimeetupil järgmisel neljapäeval.

**Comment by boamaod** [comment]
Tallinnaga seotud materjale on https://github.com/okestonia/esindus/issues/41 ja https://github.com/okestonia/opendata-issue-tracker/blob/master/files/Avaandmed_Tallinn.pdf. Kuidas see plaan haagib senise tööga ja mis on selle plaani täpsem kirjeldus?

**Comment by teelepehk** [comment]
Siin on kirjeldus, millist teenust NULA inkubaatoris välja töötame: https://github.com/okestonia/andmeusk/issues/4

**Comment by pilbastex** [comment]
Toomas Haidaku (Tallinna Strateegiabüroo juht) sõnul on neil sarnane, KOV-ide andmepädevuse tõstmise projekt käimas koos Statistikaametiga ja praegu jäi kokkulepe, et hoiame üksteist arengutega kursis. Nimetatud projekt Statistikaametiga on aastatepikkune protsess ja me saame olla oma paindlikkusega abiks tekkivate lünkade jooksval täitmisel.

**Comment by pilbastex** [comment]
Võtame Talllinna Strateegiabürooga ühendust, kui meil on selja taga esimene võrreldav koostöö arengu/tegevuskava andmete juhtimise ja visualiseerimisega.
