### ISSUE TITLE
19. juunil NULAs vahehindamine - slaidid + pitš 14. juuniks valmis!

### ISSUE THREAD

**Issue by teelepehk** [okestonia/andmekool#7]
**19. juunil kell 10.00 - 10.15 vahehindamine**
ilmselt Palo Altos Telliskivi Loomelinnakus

Iga algatust võib esitleda 1 või mitu inimest meeskonnast. Anname Marleenile eelnevalt teada, kes minemas! Oleme esimene esitleja. 

3 min slaidide selgitamiseks + 10 min arutelu.  
Kuulab nõuandev kogu (Marleen, Pirkko Valge, Mari-Liis Dolenko, Agu Laius, Marge Maidla, Priit Mikelsaar ja Martin Villig ehk sama seltskond, kes kuulas esimesi pitche). Nad saavad meie slaide juba varem näha. 

**14. juunil kella 12-ks Marleenile saata täidetud slaidid:** 
Nelja slaidi põhja (võtke see aluseks küsimuste osas, aga kui soovite, võite vorminduse osas mängida), millel palun teil lühidalt kirjeldada 1) probleemi ja lahendust (just seda, millisena täna lahendust näete ehk mida tänase parima äranägemise järgi probleemi lahendamiseks teete); 2) mida inkubaatoris tegite/testisite (siin koolitusi pole vaja loetleda, seda me teame nii ehk naa, aga just et mida vahepealsel ajal testisite) ja mida teada saite/õppisite oma lahenduse kohta; 3) oma meeskonda ja meeskonnaliikmete rolle; 4) teie eesmärke järgmiseks neljaks kuuks inkubaatoris.

Meie slaidid: https://docs.google.com/presentation/d/1UqIi3eikiG-Vw2U0IEwI4YWpdzxR4OPE/edit#slide=id.p1

**Comment by infokujur** [comment]
https://andmeusk.voog.com/ - pildid teeme siia.

**Comment by teelepehk** [comment]
Vahehindamiselt pääsesime edasi! Nüüd veel paar koolitust ja varsti ongi andmekooli teenused küpsed laiaks müümiseks.
